"""initial data layer

Revision ID: e2a671f0f512
Revises: 
Create Date: 2026-08-21 22:44:33.761165
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'e2a671f0f512'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('ticker', sa.String(length=32), nullable=True),
    sa.Column('exchange', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index('ix_companies_ticker', ['ticker'], unique=False)
        batch_op.create_index('uq_companies_ticker_exchange', ['ticker', 'exchange'], unique=True, sqlite_where=sa.text('ticker IS NOT NULL'), postgresql_where=sa.text('ticker IS NOT NULL'))
    # Case-insensitive duplicate guard + search support (expression indexes
    # are not reflected by the SQLite dialect, so they are added manually).
    # Expressions are double-parenthesized: MySQL functional key parts
    # require it; SQLite/PostgreSQL tolerate the extra level.
    op.create_index('uq_companies_legal_name_lower', 'companies', [sa.text('(lower(legal_name))')], unique=True)
    op.create_index('ix_companies_display_name_lower', 'companies', [sa.text('(lower(display_name))')], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('reporting_period_start', sa.Date(), nullable=True),
    sa.Column('reporting_period_end', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.String(length=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('reporting_period_end IS NULL OR reporting_period_start IS NULL OR reporting_period_end >= reporting_period_start', name=op.f('ck_documents_ck_documents_period_order')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_documents_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_document_type'), ['document_type'], unique=False)
        batch_op.create_index('ix_documents_filing_date', ['filing_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_fiscal_year'), ['fiscal_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index('uq_documents_company_file_hash', ['company_id', 'file_hash'], unique=True, sqlite_where=sa.text('file_hash IS NOT NULL'), postgresql_where=sa.text('file_hash IS NOT NULL'))

    op.create_table('document_pages',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('page_number >= 1', name=op.f('ck_document_pages_ck_document_pages_number_positive')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_pages_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_pages'))
    )
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_pages_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_pages_page_number'), ['page_number'], unique=False)
        batch_op.create_index('uq_document_pages_doc_page', ['document_id', 'page_number'], unique=True)

    op.create_table('document_sections',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('parent_section_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('section_title', sa.String(length=512), nullable=False),
    sa.Column('section_type', sa.String(length=64), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('page_end IS NULL OR page_start IS NULL OR page_end >= page_start', name=op.f('ck_document_sections_ck_document_sections_page_order')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_sections_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_section_id'], ['document_sections.id'], name=op.f('fk_document_sections_parent_section_id_document_sections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_sections'))
    )
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_sections_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_sections_parent_section_id'), ['parent_section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_sections_section_type'), ['section_type'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name=op.f('ck_document_chunks_ck_document_chunks_index_positive')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], name=op.f('fk_document_chunks_section_id_document_sections'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks'))
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_chunk_type'), ['chunk_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_section_id'), ['section_id'], unique=False)
        batch_op.create_index('uq_document_chunks_doc_index', ['document_id', 'chunk_index'], unique=True)

    op.create_table('financial_metrics',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_metric_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.String(length=2), nullable=True),
    sa.Column('metric_type', sa.String(length=32), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_chunk_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_financial_metrics_ck_financial_metrics_confidence_range')),
    sa.CheckConstraint('period_end IS NULL OR period_start IS NULL OR period_end >= period_start', name=op.f('ck_financial_metrics_ck_financial_metrics_period_order')),
    sa.CheckConstraint('value = value', name=op.f('ck_financial_metrics_ck_financial_metrics_value_finite')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_financial_metrics_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_financial_metrics_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], name=op.f('fk_financial_metrics_source_chunk_id_document_chunks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_metrics'))
    )
    with op.batch_alter_table('financial_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_financial_metrics_company_fiscal', ['company_id', 'fiscal_year', 'fiscal_quarter'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_metrics_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_financial_metrics_company_metric_period', ['company_id', 'normalized_metric_name', 'period_start', 'period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_metrics_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_metrics_fiscal_year'), ['fiscal_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_metrics_metric_type'), ['metric_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_metrics_source_chunk_id'), ['source_chunk_id'], unique=False)

    op.create_table('financial_tables',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('source_chunk_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('headers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('extraction_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('extraction_confidence IS NULL OR (extraction_confidence >= 0 AND extraction_confidence <= 1)', name=op.f('ck_financial_tables_ck_financial_tables_confidence_range')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_financial_tables_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], name=op.f('fk_financial_tables_source_chunk_id_document_chunks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_tables'))
    )
    with op.batch_alter_table('financial_tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_tables_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_tables_page_number'), ['page_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_tables_source_chunk_id'), ['source_chunk_id'], unique=False)

    op.create_table('financial_table_rows',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('table_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('row_label', sa.String(length=512), nullable=True),
    sa.Column('cells', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('row_index >= 0', name=op.f('ck_financial_table_rows_ck_financial_table_rows_index_positive')),
    sa.ForeignKeyConstraint(['table_id'], ['financial_tables.id'], name=op.f('fk_financial_table_rows_table_id_financial_tables'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_table_rows'))
    )
    with op.batch_alter_table('financial_table_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_table_rows_table_id'), ['table_id'], unique=False)
        batch_op.create_index('uq_financial_table_rows_table_index', ['table_id', 'row_index'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_table_rows', schema=None) as batch_op:
        batch_op.drop_index('uq_financial_table_rows_table_index')
        batch_op.drop_index(batch_op.f('ix_financial_table_rows_table_id'))

    op.drop_table('financial_table_rows')
    with op.batch_alter_table('financial_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_tables_source_chunk_id'))
        batch_op.drop_index(batch_op.f('ix_financial_tables_page_number'))
        batch_op.drop_index(batch_op.f('ix_financial_tables_document_id'))

    op.drop_table('financial_tables')
    with op.batch_alter_table('financial_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_metrics_source_chunk_id'))
        batch_op.drop_index(batch_op.f('ix_financial_metrics_metric_type'))
        batch_op.drop_index(batch_op.f('ix_financial_metrics_fiscal_year'))
        batch_op.drop_index(batch_op.f('ix_financial_metrics_document_id'))
        batch_op.drop_index('ix_financial_metrics_company_metric_period')
        batch_op.drop_index(batch_op.f('ix_financial_metrics_company_id'))
        batch_op.drop_index('ix_financial_metrics_company_fiscal')

    op.drop_table('financial_metrics')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index('uq_document_chunks_doc_index')
        batch_op.drop_index(batch_op.f('ix_document_chunks_section_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_chunk_type'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_sections_section_type'))
        batch_op.drop_index(batch_op.f('ix_document_sections_parent_section_id'))
        batch_op.drop_index(batch_op.f('ix_document_sections_document_id'))

    op.drop_table('document_sections')
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.drop_index('uq_document_pages_doc_page')
        batch_op.drop_index(batch_op.f('ix_document_pages_page_number'))
        batch_op.drop_index(batch_op.f('ix_document_pages_document_id'))

    op.drop_table('document_pages')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('uq_documents_company_file_hash', sqlite_where=sa.text('file_hash IS NOT NULL'), postgresql_where=sa.text('file_hash IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_documents_processing_status'))
        batch_op.drop_index(batch_op.f('ix_documents_fiscal_year'))
        batch_op.drop_index('ix_documents_filing_date')
        batch_op.drop_index(batch_op.f('ix_documents_document_type'))
        batch_op.drop_index(batch_op.f('ix_documents_company_id'))

    op.drop_table('documents')
    op.drop_index('ix_companies_display_name_lower', table_name='companies')
    op.drop_index('uq_companies_legal_name_lower', table_name='companies')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index('uq_companies_ticker_exchange', sqlite_where=sa.text('ticker IS NOT NULL'), postgresql_where=sa.text('ticker IS NOT NULL'))
        batch_op.drop_index('ix_companies_ticker')

    op.drop_table('companies')
    # ### end Alembic commands ###
